export default function BugReportPreview() {
  return (
    <section className="py-24 bg-surface relative overflow-hidden">
      <div className="absolute inset-0 grid-bg opacity-20" />
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-border to-transparent" />
      <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-border to-transparent" />

      <div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-sm mb-4">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
              <polyline points="14 2 14 8 20 8"/>
            </svg>
            Live Preview
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold text-text-primary mb-4">
            What a Real{" "}
            <span className="gradient-text">TraceBug Report</span> Looks Like
          </h2>
          <p className="text-text-muted text-lg max-w-2xl mx-auto">
            This is an actual report generated by TraceBug from the demo
            &ldquo;Vendor Update&rdquo; bug — complete, structured, and ready for a developer.
          </p>
        </div>

        {/* Report card */}
        <div className="code-block rounded-2xl overflow-hidden border-border shadow-2xl">
          {/* Report header bar */}
          <div className="flex items-center justify-between px-5 py-3 bg-[#0D0D14] border-b border-border">
            <div className="flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-red-500"></span>
              <span className="w-3 h-3 rounded-full bg-yellow-500"></span>
              <span className="w-3 h-3 rounded-full bg-green-500"></span>
              <span className="ml-3 text-text-muted text-xs font-mono">
                TraceBug Report — GitHub Issue Format
              </span>
            </div>
            <div className="flex items-center gap-3">
              <span className="text-xs text-green-400 font-mono">✓ Ready to paste</span>
            </div>
          </div>

          {/* Report content */}
          <div className="p-6 space-y-6 font-mono text-sm">
            {/* Title */}
            <div>
              <span className="text-text-primary text-lg font-bold">
                🐛 Vendor Update Fails — TypeError
              </span>
            </div>

            {/* Meta line */}
            <div className="flex flex-wrap gap-4 text-xs">
              <span>
                <span className="text-text-muted">Reported: </span>
                <span className="text-cyan-400">2026-03-12 14:23:01</span>
              </span>
              <span>
                <span className="text-text-muted">Session: </span>
                <span className="text-purple-400">tb_20260312_142301</span>
              </span>
              <span>
                <span className="text-text-muted">Duration: </span>
                <span className="text-yellow-400">18 seconds</span>
              </span>
            </div>

            {/* Environment */}
            <div>
              <div className="text-text-muted text-xs mb-2 uppercase tracking-wider">
                ── Environment ────────────────────────────
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
                {[
                  { label: "Browser", value: "Chrome 121.0.6167.85" },
                  { label: "OS", value: "Windows 11 Pro" },
                  { label: "Viewport", value: "1920 × 1080" },
                  { label: "Device", value: "Desktop" },
                  { label: "Connection", value: "4G — fast" },
                  { label: "Page", value: "/vendor" },
                  { label: "Events", value: "6 captured" },
                  { label: "Errors", value: "1 critical" },
                ].map((item) => (
                  <div key={item.label} className="bg-background/50 border border-border/50 rounded px-2 py-1.5">
                    <div className="text-text-muted text-[10px] mb-0.5">{item.label}</div>
                    <div className="text-text-primary text-xs truncate">{item.value}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Reproduction Steps */}
            <div>
              <div className="text-text-muted text-xs mb-2 uppercase tracking-wider">
                ── Steps to Reproduce ─────────────────────
              </div>
              <div className="space-y-1.5">
                {[
                  { n: "1", text: 'Navigate to ', path: "/vendor" },
                  { n: "2", text: 'Click ', btn: '"Edit"', extra: ' button (role=button, id=vendor-edit-btn)' },
                  { n: "3", text: 'Select ', val: '"Inactive"', extra: ' from Status dropdown (was: "Active")' },
                  { n: "4", text: 'Click ', btn: '"Update"', extra: ' button (type=submit)' },
                  { n: "5", text: 'Observe ', err: "TypeError thrown", extra: " in browser console" },
                ].map((step) => (
                  <div key={step.n} className="flex items-start gap-3">
                    <span className="text-primary font-bold w-4 flex-shrink-0">{step.n}.</span>
                    <span className="text-text-muted">
                      {step.text}
                      {"path" in step && <span className="text-cyan-400">{step.path}</span>}
                      {"btn" in step && <span className="text-blue-400">{step.btn}</span>}
                      {"val" in step && <span className="text-purple-400">{step.val}</span>}
                      {"err" in step && <span className="text-red-400">{step.err}</span>}
                      {"extra" in step && step.extra}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Console Errors */}
            <div>
              <div className="text-text-muted text-xs mb-2 uppercase tracking-wider">
                ── Console Errors ──────────────────────────
              </div>
              <div className="bg-red-500/5 border border-red-500/20 rounded-lg p-4 space-y-2">
                <div className="flex items-center gap-2 mb-3">
                  <span className="w-2 h-2 rounded-full bg-red-400"></span>
                  <span className="text-red-400 font-bold text-xs">TypeError — Critical</span>
                </div>
                <div className="text-red-300 text-xs">
                  Cannot read properties of undefined (reading &apos;status&apos;)
                </div>
                <div className="text-text-muted text-[11px] leading-relaxed mt-2">
                  <div className="text-yellow-400/70">Stack trace:</div>
                  <div className="pl-3 space-y-0.5 mt-1">
                    <div>at <span className="text-blue-400">updateVendor</span> (vendor/page.tsx:<span className="text-yellow-400">42</span>:<span className="text-yellow-400">18</span>)</div>
                    <div>at <span className="text-blue-400">handleSubmit</span> (vendor/page.tsx:<span className="text-yellow-400">67</span>:<span className="text-yellow-400">5</span>)</div>
                    <div>at <span className="text-blue-400">onClick</span> (vendor/page.tsx:<span className="text-yellow-400">112</span>:<span className="text-yellow-400">24</span>)</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Network Log */}
            <div>
              <div className="text-text-muted text-xs mb-2 uppercase tracking-wider">
                ── Network Log ─────────────────────────────
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="text-text-muted border-b border-border">
                      <th className="text-left py-1.5 pr-4">Method</th>
                      <th className="text-left py-1.5 pr-4">URL</th>
                      <th className="text-left py-1.5 pr-4">Status</th>
                      <th className="text-left py-1.5 pr-4">Duration</th>
                      <th className="text-left py-1.5">Time</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      { method: "GET", url: "/api/vendor/123", status: "200", statusColor: "text-green-400", dur: "124ms", time: "+0.3s" },
                      { method: "POST", url: "/api/vendor/update", status: "500", statusColor: "text-red-400", dur: "89ms", time: "+3.5s" },
                    ].map((row, i) => (
                      <tr key={i} className="border-b border-border/50">
                        <td className="py-2 pr-4">
                          <span className={`${row.method === "GET" ? "text-cyan-400" : "text-yellow-400"} font-bold`}>
                            {row.method}
                          </span>
                        </td>
                        <td className="py-2 pr-4 text-text-muted">{row.url}</td>
                        <td className={`py-2 pr-4 font-bold ${row.statusColor}`}>{row.status}</td>
                        <td className="py-2 pr-4 text-text-muted">{row.dur}</td>
                        <td className="py-2 text-text-muted">{row.time}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Session Timeline */}
            <div>
              <div className="text-text-muted text-xs mb-2 uppercase tracking-wider">
                ── Session Timeline ─────────────────────────
              </div>
              <div className="space-y-1.5">
                {[
                  { t: "+0.0s", type: "navigate", color: "text-cyan-400", icon: "→", detail: "/ → /vendor" },
                  { t: "+1.2s", type: "click", color: "text-blue-400", icon: "●", detail: 'button "Edit" [id=vendor-edit-btn]' },
                  { t: "+2.1s", type: "select", color: "text-purple-400", icon: "◆", detail: 'Status: "Active" → "Inactive"' },
                  { t: "+3.4s", type: "click", color: "text-blue-400", icon: "●", detail: 'button "Update" [type=submit]' },
                  { t: "+3.5s", type: "api", color: "text-yellow-400", icon: "⟳", detail: "POST /api/vendor/update → 500" },
                  { t: "+3.5s", type: "error", color: "text-red-400", icon: "✕", detail: "TypeError: Cannot read 'status'" },
                ].map((event, i) => (
                  <div key={i} className="flex items-center gap-3 text-xs py-0.5">
                    <span className="text-text-muted w-10 flex-shrink-0 font-mono">{event.t}</span>
                    <span className={`${event.color} w-4 flex-shrink-0 text-center`}>{event.icon}</span>
                    <span className={`${event.color} font-semibold w-16 flex-shrink-0`}>{event.type}</span>
                    <span className="text-text-muted truncate">{event.detail}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Export options */}
            <div className="border-t border-border pt-4 flex flex-wrap gap-2">
              {[
                { label: "Copy GitHub Issue", color: "bg-primary/20 border-primary/30 text-primary hover:bg-primary/30" },
                { label: "Copy Jira Ticket", color: "bg-blue-500/20 border-blue-500/30 text-blue-400 hover:bg-blue-500/30" },
                { label: "Download PDF", color: "bg-green-500/20 border-green-500/30 text-green-400 hover:bg-green-500/30" },
                { label: "Download JSON", color: "bg-yellow-500/20 border-yellow-500/30 text-yellow-400 hover:bg-yellow-500/30" },
              ].map((btn) => (
                <button
                  key={btn.label}
                  className={`px-3 py-1.5 text-xs font-medium border rounded-lg transition-colors ${btn.color}`}
                >
                  {btn.label}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
