// ── GitHub issue template generator ───────────────────────────────────────
// Generates GitHub-flavored markdown for bug issues.
// Copy-paste ready — includes all debugging context.

import { BugReport } from "./types";
import { formatTimelineText } from "./timeline-builder";

export function generateGitHubIssue(report: BugReport): string {
  const env = report.environment;

  let md = `## ${report.title}\n\n`;

  // Environment
  md += `**Environment:** ${env.browser} ${env.browserVersion} / ${env.os} / ${env.viewport}\n`;
  md += `**Page:** ${env.url}\n`;
  md += `**Device:** ${env.deviceType}\n`;
  md += `**Date:** ${new Date(report.generatedAt).toLocaleString()}\n\n`;

  // Steps to Reproduce
  md += `### Steps to Reproduce\n\n`;
  if (report.steps) {
    md += `${report.steps}\n\n`;
  } else {
    md += `_No steps recorded_\n\n`;
  }

  // Tester Notes (Annotations)
  if (report.annotations.length > 0) {
    md += `### Tester Notes\n\n`;
    for (const note of report.annotations) {
      md += `- **[${note.severity.toUpperCase()}]** ${note.text}\n`;
      if (note.expected) md += `  - **Expected:** ${note.expected}\n`;
      if (note.actual) md += `  - **Actual:** ${note.actual}\n`;
    }
    md += `\n`;
  }

  // Expected vs Actual (from first critical annotation)
  const criticalNote = report.annotations.find(a => a.expected || a.actual);
  if (criticalNote) {
    md += `### Expected Result\n\n${criticalNote.expected || "_Not specified_"}\n\n`;
    md += `### Actual Result\n\n${criticalNote.actual || "_Not specified_"}\n\n`;
  } else if (report.consoleErrors.length > 0) {
    md += `### Actual Result\n\n`;
    md += `Application throws error: \`${report.consoleErrors[0].message}\`\n\n`;
  }

  // Console Errors
  if (report.consoleErrors.length > 0) {
    md += `### Console Errors\n\n`;
    md += `\`\`\`\n`;
    for (const err of report.consoleErrors.slice(0, 5)) {
      md += `${err.message}\n`;
      if (err.stack) md += `${err.stack.split("\n").slice(0, 3).join("\n")}\n`;
      md += `\n`;
    }
    md += `\`\`\`\n\n`;
  }

  // Network Errors
  if (report.networkErrors.length > 0) {
    md += `### Failed Network Requests\n\n`;
    md += `| Method | URL | Status | Duration |\n`;
    md += `|--------|-----|--------|----------|\n`;
    for (const req of report.networkErrors) {
      const status = req.status === 0 ? "Network Error" : `${req.status}`;
      const url = req.url.length > 60 ? req.url.slice(0, 57) + "..." : req.url;
      md += `| ${req.method} | \`${url}\` | ${status} | ${req.duration}ms |\n`;
    }
    md += `\n`;
  }

  // Screenshots
  if (report.screenshots.length > 0) {
    md += `### Screenshots\n\n`;
    md += `_${report.screenshots.length} screenshot(s) captured — see attached files_\n\n`;
    for (const ss of report.screenshots) {
      md += `- \`${ss.filename}\` — ${ss.eventContext} (${ss.page})\n`;
    }
    md += `\n`;
  }

  // Session Timeline (collapsed)
  if (report.timeline.length > 0) {
    md += `### Session Timeline\n\n`;
    md += `<details>\n<summary>View full timeline (${report.timeline.length} events)</summary>\n\n`;
    md += `\`\`\`\n`;
    md += formatTimelineText(report.timeline);
    md += `\n\`\`\`\n\n`;
    md += `</details>\n\n`;
  }

  // Session Metadata
  md += `---\n`;
  md += `_Generated by [TraceBug SDK](https://www.npmjs.com/package/tracebug-sdk) · `;
  md += `Session: \`${report.session.sessionId.slice(0, 8)}\` · `;
  md += `${report.session.events.length} events · `;
  md += `${new Date(report.generatedAt).toLocaleString()}_\n`;

  return md;
}
