// ── Jira ticket template generator ────────────────────────────────────────
// Generates Jira-compatible ticket content.
// Returns both structured payload and formatted description text.

import { BugReport } from "./types";
import { formatTimelineText } from "./timeline-builder";

export interface JiraTicket {
  summary: string;
  description: string;
  environment: string;
  stepsToReproduce: string;
  priority: "Highest" | "High" | "Medium" | "Low" | "Lowest";
  labels: string[];
}

export function generateJiraTicket(report: BugReport): JiraTicket {
  const env = report.environment;
  const priority = determinePriority(report);

  // Labels based on error type
  const labels: string[] = ["tracebug", "bug"];
  if (report.consoleErrors.length > 0) labels.push("has-errors");
  if (report.networkErrors.length > 0) labels.push("api-failure");

  // Environment string
  const envStr = `${env.browser} ${env.browserVersion} / ${env.os} / ${env.viewport} / ${env.deviceType}`;

  // Description
  let desc = "";

  // Steps
  desc += `h3. Steps to Reproduce\n`;
  if (report.steps) {
    desc += `{noformat}\n${report.steps}\n{noformat}\n\n`;
  }

  // Tester notes
  if (report.annotations.length > 0) {
    desc += `h3. Tester Notes\n`;
    for (const note of report.annotations) {
      desc += `* *[${note.severity.toUpperCase()}]* ${note.text}\n`;
      if (note.expected) desc += `** *Expected:* ${note.expected}\n`;
      if (note.actual) desc += `** *Actual:* ${note.actual}\n`;
    }
    desc += `\n`;
  }

  // Expected/Actual
  const criticalNote = report.annotations.find(a => a.expected || a.actual);
  if (criticalNote) {
    desc += `h3. Expected Result\n${criticalNote.expected || "_Not specified_"}\n\n`;
    desc += `h3. Actual Result\n${criticalNote.actual || "_Not specified_"}\n\n`;
  } else if (report.consoleErrors.length > 0) {
    desc += `h3. Actual Result\nApplication throws error:\n{code}${report.consoleErrors[0].message}{code}\n\n`;
  }

  // Console errors
  if (report.consoleErrors.length > 0) {
    desc += `h3. Console Errors\n{code}\n`;
    for (const err of report.consoleErrors.slice(0, 5)) {
      desc += `${err.message}\n`;
      if (err.stack) desc += `${err.stack.split("\n").slice(0, 3).join("\n")}\n`;
    }
    desc += `{code}\n\n`;
  }

  // Network errors
  if (report.networkErrors.length > 0) {
    desc += `h3. Failed Network Requests\n`;
    desc += `||Method||URL||Status||Duration||\n`;
    for (const req of report.networkErrors) {
      const status = req.status === 0 ? "Network Error" : String(req.status);
      desc += `|${req.method}|${req.url.slice(0, 80)}|${status}|${req.duration}ms|\n`;
    }
    desc += `\n`;
  }

  // Screenshots
  if (report.screenshots.length > 0) {
    desc += `h3. Screenshots\n`;
    desc += `${report.screenshots.length} screenshot(s) captured:\n`;
    for (const ss of report.screenshots) {
      desc += `* {{${ss.filename}}} — ${ss.eventContext}\n`;
    }
    desc += `\n`;
  }

  // Timeline (collapsed)
  if (report.timeline.length > 0) {
    desc += `h3. Session Timeline\n{code}\n`;
    desc += formatTimelineText(report.timeline);
    desc += `\n{code}\n\n`;
  }

  // Environment details
  desc += `h3. Environment\n`;
  desc += `* *Browser:* ${env.browser} ${env.browserVersion}\n`;
  desc += `* *OS:* ${env.os}\n`;
  desc += `* *Viewport:* ${env.viewport}\n`;
  desc += `* *Device:* ${env.deviceType}\n`;
  desc += `* *Connection:* ${env.connectionType}\n`;
  desc += `* *URL:* ${env.url}\n\n`;

  desc += `----\n_Generated by TraceBug SDK · Session: ${report.session.sessionId.slice(0, 8)}_\n`;

  return {
    summary: report.title,
    description: desc,
    environment: envStr,
    stepsToReproduce: report.steps || "",
    priority,
    labels,
  };
}

function determinePriority(report: BugReport): JiraTicket["priority"] {
  // Critical errors (TypeError, ReferenceError) = Highest
  const hasCriticalError = report.consoleErrors.some(e =>
    /TypeError|ReferenceError|SyntaxError/i.test(e.message)
  );
  if (hasCriticalError) return "Highest";

  // Server errors (5xx) = High
  const hasServerError = report.networkErrors.some(r => r.status >= 500);
  if (hasServerError) return "High";

  // Client errors (4xx) or network failures = Medium
  if (report.networkErrors.length > 0) return "Medium";

  // Console errors only = Low
  if (report.consoleErrors.length > 0) return "Low";

  // Tester-reported annotation = Medium
  if (report.annotations.some(a => a.severity === "critical" || a.severity === "major")) return "Medium";

  return "Low";
}
